### PR TITLE
Adding CI and using new aggregated sdk docs setup

### LINKED ISSUE #17: Add CI to sdk-juzu

### PR DESCRIPTION
**Pull request by shahruk10**
Closes #17 

- Updates doc src files for hugo version >= 0.69
- Removes hugo and autogenerated docs from this repo in favor of using aggregated sdk-docs
- Adds CI
- Updates go version to 1.16.2; this required a fix to the TLS tests since Go >= 1.15 dropped support for verifying hostname/IP address in the Common Name field of a certificate. It now requires that the hostname be present in Subject Alternative Names (SAN) extension. See golang/go#39568 (comment)

### CODE REVIEW

**Review by mplooster — APPROVED** [review]
LGTM. Do we need to set up Render to automatically generate docs on this repo now for PRs, etc?

**Comment by shahruk10** [comment]
> LGTM. Do we need to set up Render to automatically generate docs on this repo now for PRs, etc?

Yes, I think all it would take is updating the cobaltspeech.github.io repo after merging this into master?

**Comment by mplooster** [comment]
> Yes, I think all it would take is updating the cobaltspeech.github.io repo after merging this into master?

That should be all it takes to get it to appear on docs.cobaltspeech.com. If you want an automatic render to show up in PRs and such, I think we need set it up in Render still.

**Comment by shahruk10** [comment]
Closing and Reopening this PR to trigger Render to automatically generate docs preview on this repo.

**Pull request closed without merging**
